[package]
name = "oma-overlay"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "OpenMonitor Advanced overlay"

[build-dependencies]
tauri-winres = "0.3"

[dependencies]
oma-core.workspace = true
oma-ipc.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"

[target.'cfg(windows)'.dependencies]
oma-win.workspace = true

[dev-dependencies]
serde_json.workspace = true
