[package]
name = "oma-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
oma-ipc.workspace = true
thiserror.workspace = true
tracing.workspace = true
twox-hash = { version = "2.1", default-features = false, features = ["xxhash3_64"] }

