import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';
import type {
  AppInfo,
  ExportedReport,
  AutostartStatus,
  GpuProcess,
  HealthClock,
  HealthReport,
  HistorySeed,
  Schema,
  ServiceStatus,
  Session,
  SettingsState,
  Snapshot,
  DiskStateEntry,
  StartupStatus,
  StatsReply,
  NavigationTarget,
  Rule,
  RuleStatus,
  LogStatus,
  OverlayStatus,
  UpdateStatus,
  BenchmarkEntry,
  EditableProfile,
  EditorData,
} from '../types';
import type { Backend } from './backend';

/** Command and event names are defined in app/src-tauri (commands.rs, main.rs). */
export function createTauriBackend(): Backend {
  return {
    getSchema: () => invoke<Schema>('get_schema'),
    // Tauri maps the camelCase `maxPoints` key to the `max_points` argument; a missing key is `None`.
    getHistory: (ids, seconds, maxPoints) =>
      invoke<HistorySeed>('get_history', maxPoints === undefined ? { ids, seconds } : { ids, seconds, maxPoints }),
    onSchema: (cb) => listen<Schema>('oma:schema', (e) => cb(e.payload)),
    onSnapshot: (cb) => listen<Snapshot>('oma:snapshot', (e) => cb(e.payload)),
    getDiskStates: () => invoke<DiskStateEntry[]>('get_disk_states'),
    onDiskStates: (cb) => listen<DiskStateEntry[]>('oma:disk-states', (e) => cb(e.payload)),
    getStartupStatus: () => invoke<StartupStatus>('get_startup_status'),
    enableVendorLibraries: () => invoke<StartupStatus>('enable_vendor_libraries'),
    getStats: (ids) => invoke<StatsReply>('get_stats', { ids }),
    resetStats: (ids) => invoke<void>('reset_stats', { ids }),
    getSession: () => invoke<Session>('get_session'),
    getGpuProcesses: (deviceId) => invoke<GpuProcess[]>('get_gpu_processes', { deviceId }),
    getServiceStatus: () => invoke<ServiceStatus>('get_service_status'),
    onServiceStatus: (cb) => listen<ServiceStatus>('oma:service', (e) => cb(e.payload)),
    setAntiCheat: (enabled) => invoke<ServiceStatus>('set_anti_cheat', { enabled }),
    startService: () => invoke<ServiceStatus>('start_service'),
    getSettings: () => invoke<SettingsState>('get_settings'),
    // A rejected patch arrives as the serialized `{ field, key }` object.
    updateSettings: (patch) => invoke<SettingsState>('update_settings', { patch }),
    resetRuleOverride: (ruleId) => invoke<SettingsState>('reset_rule_override', { ruleId }),
    onSettings: (cb) => listen<SettingsState>('oma:settings', (e) => cb(e.payload)),
    importWebviewState: (legacy) => invoke<SettingsState>('import_webview_state', { legacy }),
    takePendingView: () => invoke<NavigationTarget | null>('take_pending_view'),
    onNavigate: (cb) => listen<NavigationTarget>('oma:navigate', (e) => cb(e.payload)),
    getHealth: () => invoke<HealthReport>('get_health'),
    onHealth: (cb) => listen<HealthReport>('oma:health', (e) => cb(e.payload)),
    getHealthClock: () => invoke<HealthClock>('get_health_clock'),
    onHealthClock: (cb) => listen<HealthClock>('oma:health-clock', (e) => cb(e.payload)),
    getRuleStatus: () => invoke<RuleStatus[]>('get_rule_status'),
    getDefaultRules: () => invoke<Rule[]>('get_default_rules'),
    refreshAutostart: () => invoke<AutostartStatus>('refresh_autostart'),
    getAppInfo: () => invoke<AppInfo>('get_app_info'),
    // A unit variant of `KnownPath`: the camelCase string is the whole value.
    openKnownPath: (target) => invoke<void>('open_known_path', { target }),
    getLogStatus: () => invoke<LogStatus>('get_log_status'),
    onLogStatus: (cb) => listen<LogStatus>('oma:log', (e) => cb(e.payload)),
    logStart: () => invoke<LogStatus>('log_start'),
    logPause: () => invoke<LogStatus>('log_pause'),
    logResume: () => invoke<LogStatus>('log_resume'),
    logStop: () => invoke<LogStatus>('log_stop'),
    openLogFolder: () => invoke<void>('open_log_folder'),
    pickLogFolder: () => invoke<string | null>('pick_log_folder'),
    setLogHotkeysSuspended: (suspended) => invoke<void>('set_log_hotkeys_suspended', { suspended }),
    getOverlayStatus: () => invoke<OverlayStatus | null>('get_overlay_status'),
    onOverlayStatus: (cb) => listen<OverlayStatus>('overlay-status', (e) => cb(e.payload)),
    overlayRetry: () => invoke<void>('overlay_retry'),
    overlayReloadProfiles: () => invoke<void>('overlay_reload_profiles'),
    setOverlayHidden: (hidden) => invoke<void>('set_overlay_hidden', { hidden }),
    overlayLoadProfile: (id) => invoke<EditableProfile>('overlay_load_profile', { id }),
    // A null `id` is `None`: a new profile.
    overlaySaveProfile: (id, json) => invoke<string>('overlay_save_profile', { id, json }),
    overlayDeleteProfile: (id) => invoke<void>('overlay_delete_profile', { id }),
    overlayDuplicateProfile: (id) => invoke<string>('overlay_duplicate_profile', { id }),
    overlayImportProfile: () => invoke<string | null>('overlay_import_profile'),
    overlayExportProfile: (id) => invoke<boolean>('overlay_export_profile', { id }),
    overlayFontFamilies: () => invoke<string[]>('overlay_font_families'),
    overlayPreview: (json) => invoke<void>('overlay_preview', { json }),
    overlayEditorProfile: (json) => invoke<void>('overlay_editor_profile', { json }),
    overlayUseNow: (id) => invoke<void>('overlay_use_now', { id }),
    overlayEditorDirty: (dirty) => invoke<void>('overlay_editor_dirty', { dirty }),
    openOverlayEditor: () => invoke<void>('open_overlay_editor'),
    appQuitConfirmed: () => invoke<void>('app_quit_confirmed'),
    onOverlayEditorData: (cb) => listen<EditorData>('overlay-editor-data', (e) => cb(e.payload)),
    onOverlayPreview: (cb) => listen<{ open: boolean }>('overlay-preview', (e) => cb(e.payload)),
    onOverlayEditorQuit: (cb) => listen<null>('overlay-editor-quit', () => cb()),
    benchmarkToggle: () => invoke<void>('benchmark_toggle'),
    benchmarkList: () => invoke<BenchmarkEntry[]>('benchmark_list'),
    benchmarkOpenCsv: (id) => invoke<void>('benchmark_open_csv', { id }),
    benchmarkOpenFolder: () => invoke<void>('benchmark_open_folder'),
    benchmarkDelete: (id) => invoke<void>('benchmark_delete', { id }),
    checkUpdates: () => invoke<UpdateStatus>('check_updates'),
    getUpdateStatus: () => invoke<UpdateStatus>('get_update_status'),
    openReleasePage: () => invoke<void>('open_release_page'),
    onUpdateStatus: (cb) => listen<UpdateStatus>('oma:update-status', (e) => cb(e.payload)),
    exportSensorReport: () => invoke<ExportedReport | null>('export_sensor_report'),
    revealSensorReport: () => invoke<void>('reveal_sensor_report'),
  };
}
